listForecast:
  handler: src/forecast/forecast.list_forecast
  events:
    - http:
        path: /forecast
        method: POST
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
        # authorizer:
        #   arn: arn:aws:cognito-idp:us-east-1:453299555282:userpool/us-east-1_RMpcwKhiW
