queryResults:
  handler: src/query/results.queryRes
  events:
    - http:
        path: /query_result
        method: GET
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
        # authorizer:
        #   arn: arn:aws:cognito-idp:us-east-1:453299555282:userpool/us-east-1_RMpcwKhiW
