createStore:
  handler: src/stores/stores.create
  events:
    - http:
        path: /stores
        method: POST
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
        # authorizer:
        #   arn: arn:aws:cognito-idp:us-east-1:453299555282:userpool/us-east-1_RMpcwKhiW

getSingleStore:
  handler: src/stores/stores.get_single
  events:
    - http:
        path: /stores/{store_id}
        method: GET
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
        # authorizer:
        #   arn: arn:aws:cognito-idp:us-east-1:453299555282:userpool/us-east-1_RMpcwKhiW

updateStore:
  handler: src/stores/stores.put
  events:
    - http:
        path: /stores/{store_id}
        method: PUT
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
        # authorizer:
        #   arn: arn:aws:cognito-idp:us-east-1:453299555282:userpool/us-east-1_RMpcwKhiW
